### ISSUE TITLE
[doc] Possible minor improvements to mathtools

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/mathtools#10]
Sorry to bother you for such minor things. And sorry for opening this issue since I am not confident enough to open a PR.

1. Spaces used in the showcases of `\xmathstrut` is not that consistent.
i. The spaces before `-`  in `\sqrt{ 1 -x }` and before `>` in `$x >0$` is a bit wired to me, and not consistent with other examples in the same doc.
https://github.com/latex3/mathtools/blob/4c36964f7244edfc97ec8c81149d4ced699dbb4d/mathtools.dtx#L2786-L2798

     ii. Extra spaces are found after `\xmathstrut{0.5}` and `\xmathstrut{-0.1}`, but not for other two showcases.
https://github.com/latex3/mathtools/blob/4c36964f7244edfc97ec8c81149d4ced699dbb4d/mathtools.dtx#L2809-L2816

2. Name of documentation _Math mode_ on CTAN is now available as `Mathmode.pdf`, not `Voss-Mathmode.pdf`. Check the link http://mirrors.ctan.org/obsolete/info/math/voss/mathmode/Mathmode.pdf on page https://ctan.org/tex-archive/obsolete/info/math/voss/mathmode.
https://github.com/latex3/mathtools/blob/4c36964f7244edfc97ec8c81149d4ced699dbb4d/mathtools.dtx#L2955-L2959

3. The link to _Mathematics into type_ now supports `https`.
https://github.com/latex3/mathtools/blob/4c36964f7244edfc97ec8c81149d4ced699dbb4d/mathtools.dtx#L2961-L2966

**Comment by daleif** [comment]
I'd rather have these as issues not PRs (as I'm not comfortable with them either)
Regarding 1i+ii I don't quire follow what you are referring to. Is the the verbatim code?

I'll update 2 and 3

**Comment by muzimuzhi** [comment]
> Regarding 1i+ii I don't quire follow what you are referring to. Is the the verbatim code?

Yes, I am talking about the verbatim code.

![image](https://user-images.githubusercontent.com/6376638/85427849-ea6a6680-b5ae-11ea-9d2f-034e2c094688.png)
![image](https://user-images.githubusercontent.com/6376638/85427917-feae6380-b5ae-11ea-99b9-bff300b5cc7d.png)

**Comment by daleif** [comment]
Ok, I'll stream line that a bit

**Comment by daleif** [comment]
That should not be fixed. It will come out at some point.
Thanks for the comments

**Comment by muzimuzhi** [comment]
Thanks.

I also opened a pull request #9 which tries to fix some typo in doc. Would you please have a look at it?

**Comment by daleif** [comment]
I'm not well versed in git, so I'd rather have then as issues such that I know where and exactly why

**Comment by daleif** [comment]
Had a look at it, seemed fine, merged.
