### ISSUE TITLE
Incompatibility with pdfx

### ISSUE THREAD

**Issue by merkste** [latex3/mathtools#11]
If pdfx and mathtools are loaded at the same time, some math operators break. For example, \dot is not centered above operators anymore. See the minimal example below.

    \documentclass{book}
    
    \RequirePackage[a-1b]{pdfx}
    \RequirePackage{mathtools}
    
    \begin{document}
    \[
      A \dot\cup B
    \]
    \end{document}

**Comment by u-fischer** [comment]
that is a pdfx problem. It patches some command of amsmath and breaks them. See also
https://tex.stackexchange.com/a/512646/2388. The patch used there helps also in your case, but pdfx should better correct or remove its patch.

**Comment by daleif** [comment]
Closed as it is not a mathtools issue

**Comment by merkste** [comment]
@u-fischer Thanks for pointing me to the workaround. FYI: The authors of pdfx told me that only version 1.6.3 is affected and that the next update will fix the issue.
