### ISSUE TITLE
[feature-request] Please provide \xlongleftarrow and \xlongrightarrow

### ISSUE THREAD

**Issue by rbrito** [latex3/mathtools#12]
I see that the extensible arrows that `mathtools` offers are great, but when you want to typeset something like `$X \xrightarrow{\phi} Y$`, the arrow is too short.

With the package `extarrows`, you can use a version of the command from `mathtools` that provides a slightly longer arrow as `$X \xlongrightarrow{\phi} Y$`. Could something like this be included in `mathtools`, so that the package becomes more complete?

**Comment by daleif** [comment]
I'm having a hard time seeing the point of those. From the `extarrows` sample PDF it seems to be that the only difference between `\xlongrightarrow` and `\xrightarrow` is that `\xlongrightarrow{}` (with an empty arg is longer). There seems to be no difference when given arguments.

**Comment by rbrito** [comment]
> I'm having a hard time seeing the point of those. From the `extarrows` sample PDF it seems to be that the only difference between `\xlongrightarrow` and `\xrightarrow` is that `\xlongrightarrow{}` (with an empty arg is longer). There seems to be no difference when given arguments.

With the document attached (with txt as extension, since github only accepts a limited number of attachment types), I can see a difference when given arguments (actually, both with and without arguments). I'm attaching a screenshot here.

![screenshot-at-2020-06-26-21-59-28](https://user-images.githubusercontent.com/212145/85911072-1b96a100-b812-11ea-8d9c-ae6b33637f08.png)

If you want me to provide any extra data, please let me know.

Thanks,

Rogério Brito.

[arrows.txt](https://github.com/latex3/mathtools/files/4839766/arrows.txt)

**Comment by benjub** [comment]
Maybe use $X \xrightarrow{\;f\;} Y$ ?

**Comment by rbrito** [comment]
> Maybe use $X \xrightarrow{\;f\;} Y$ ?

Hi. Thanks for the suggestion. That didn't quite match the output that I expected, but using `$X \xrightarrow{\ f\ } Y$` did. Typing the extra `$\ $` in a whole document is tiring and it would be quite nice to have a standard, uniform way of doing that.

**Comment by daleif** [comment]
I do something similar in my own docs. It is just hard for me to come up with a default length of the arrow and when it should then start extending. 

Any suggestions?

**Comment by FrankMittelbach** [comment]
What about extending it twice compared to the difference between  rightarrow and longrightarrow? You could also think of having something like `\xarrarowfactor` (default 2) which makes the extension factor adjustable?

**Comment by FrankMittelbach** [comment]
Or that factor could be tied to one of the math font dimens so that it changes with the font size without the need to do measurements of some sort or precompute them.

**Comment by daleif** [comment]
@FrankMittelbach Not quite understood. Though I was thinking in terms of having the default size of `\xrightlongarrow` match `\rightlongarrow` if the argument is "small" and then have the arrow extend when one of the arguments is longer than a certain length.

Come to think of it, I'd also like to be able to always add a certain comfigurable padding (like the '\;' og '\ ' in the comments) to the arrow. As this is something I often do in my manuscript edits.

But it might also be useful then to have a version with less padding if used in the text.

**Comment by FrankMittelbach** [comment]
Forget my remark, I misremembered how they are defined in extarrow and amsmath. 

But yes more padding might be good. If you think of `\rightarrow` and `\longrightarrow` defining the padding (half the width of the arrow) then maybe `\xrightarrow` and `\xlongrightarrow` could keep that padding on both sides if their argument(s) grow

**Comment by rbrito** [comment]
On February 2, 2021 11:56:29 AM GMT-03:00, Frank Mittelbach <notifications@github.com> wrote:
>But yes more padding might be good. If you think of `\rightarrow` and
>`\longrightarrow` defining the padding (half the width of the arrow)
>then maybe `\xrightarrow` and `\xlongrightarrow` could keep that
>padding on both sides if their argument(s) grow

Hi, people.

Thank you very much for consideration of my request.

Thanks once again,

Rogério Brito.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daleif** [comment]
> Forget my remark, I misremembered how they are defined in extarrow and amsmath.
> 
> But yes more padding might be good. If you think of `\rightarrow` and `\longrightarrow` defining the padding (half the width of the arrow) then maybe `\xrightarrow` and `\xlongrightarrow` could keep that padding on both sides if their argument(s) grow

That is an interesting idea. I'll have a look when things calms a bit more after semester start (though so far I hasn't been as chaotic as back in August)

**Comment by daleif** [comment]
@FrankMittelbach hadn't looked at this before now, but isn't `\xlongrightarrow` as easy as

```
\def\longrightarrowfill@{\arrowfill@\relbar\relbar\longrightarrow} % following \rightarrowfill@ in amsmath
\newcommand{\xlongrightarrow}[2][]{\ext@arrow 0359\longrightarrowfill@{#1}{#2}}
```

it does exactly what @rbrito was asking for?
