### ISSUE TITLE
smashoperator seems to break beamer transparency

### ISSUE THREAD

**Issue by lesshaste** [latex3/mathtools#13]
Consider the following code:

```
\documentclass[xcolor={rgb}]{beamer}
\setbeamercovered{transparent}
\beamertemplatenavigationsymbolsempty
\setbeamersize{text margin left=10mm,text margin right=5mm}
\setbeamertemplate{frametitle}[default][center]
\usepackage{mathtools}
\usepackage{bm}
\newcommand{\var}[1]{\operatorname{var}{#1}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\norm}[1]{\left\lVert#1\right\rVert}
\begin{document}
\begin{frame}[t]
\begin{align*}
\onslide<2->{&= \E\Bigl( g(a)^2 \smashoperator{\sum_{j\in[n]\backslash\{a\}}} f^2_j Y^2_j + \smashoperator{\sum_{\substack{j\in[n]\setminus\{a\}\\i\ne j}}} f_i f_j g(i) g(j) Y_i B_j\Bigr) -{}\\}
\onslide<2->{&\qquad\qquad\qquad\qquad \Bigl(\smashoperator{\sum_{j\in[n]\backslash\{a\}}} f_j \mathbb{E}[g(a)g(j)Y_j]\Bigr)^2\\[\jot]}
\onslide<3->{&= \sum_{j\in[n]\backslash\{a\}} \frac{f^2_j}{k} + 0 - 0\\[\jot]}
\end{align*}
\end{frame}
\end{document}
```

This shows the subscripts that are covered by \smashoperator in black when they should be transparent.

@marmot at https://topanswers.xyz/tex?q=1330#a1568 has suggested a possible cause for this problem/bug.

**Comment by davidcarlisle** [comment]
Marmot's suggested fix is a fix in beamer not mathtools though.

**Comment by marmotghost** [comment]
@davidcarlisle Not really. This is just to collect evidence that the amsmath "double expansion" could have to do with that. However, it would be a bit difficult to rewrite the `\onslide` command in such a way that it scans for `\smashoperator` and tells it which box it should use. It seems much easier/more reasonable to add some `\unless\ifmeasuring@ ...\fi` to `\smashoperator`.

**Comment by davidcarlisle** [comment]
@marmotghost  hmm perhaps i misread your code, I'll look at the thread again, I thought with

```
\renewrobustcmd{\beamer@@pause}[1][]{%
  \unless\ifmeasuring@%
```

you were suggesting making the pause mechanism aware of the measuring pass so not specifically looking for `\smashoperator` ?

**Comment by marmotghost** [comment]
Well, sort of. That is, the code using `\pause` works. However, the modification of `\pause` does not fix the code with `\onslide`s. (Of course, `\pause` is based on `\onslide`.) Now you could try to modify `\onlside` in such a way that it does not do anything when measuring. This should, in principle, work (if all the guesswork was right), but will almost certainly break something. So I thought it will be easier to fix `\smashoperator` to not create the box while measuring.

**Comment by davidcarlisle** [comment]
@marmotghost  smashoperator can't do nothing in the measuring pass(as it needs to be measured, as far as I can see but perhaps I didn't follow the suggestion?

**Comment by marmotghost** [comment]
Yes, it is confusing. The `align` environment has a measuring phase, and `\smashoperator` has `\MT_smop_measure`, which, among other things, seems to create a box, to measure it, and to "save" it. I was referring to the measuring phase of `align`, and though that not saving a box in that phase may help. But of course I may be wrong. I certainly do not understand this code. (Somebody once told me that the great thing about `expl3` is that one does no longer need `\expandafter`.... ;-)

**Comment by davidcarlisle** [comment]
@marmotghost  you ask elsewhere about `\if@measuring that comes from amstex so it is older than latex2e and certainly older than beamer

**Comment by marmotghost** [comment]
@davidcarlisle Yes. I agree. But what does this have to with the problem here? (I do not think that one can just rewrite `\uncover` without breaking something, but I may be wrong.)

**Comment by davidcarlisle** [comment]
@marmotghost  yes the history comment was just a comment.. 

 I'm not sure how intrusive a change would need to be made in beamer but I'm not sure what changes could be made here (actually as I'm not sure why transparency is failing, clearly related to the multiple evaluations but...)

Abstractly beamer can avoid the problem by not doing pause or onslide or whatever during trial runs (ie when `\ifmeasuring@` is true. There may be (probably are) compatibility concerns with changing anything  there.

amsmath/mathtools can't make smashoperator (and similar commands) simply do nothing when `\ifmeasuring@` is true as then the typesetting is different and the measuring pass will return the wrong widths which negates the purpose of the double evaluation.

It could do "whatever is needed so that it measures correctly on the first pass and enables transparency on the second" but I'm not sure what that is at present. Transparency is a weird beast in PDF:-)

**Comment by marmotghost** [comment]
@davidcarlisle Yes, that's all true. Naively I would have thought that all that needs to be done is to discard a box that is created in the "intransparent" phase. Anyway, there are working workarounds around. ;-)

**Comment by lesshaste** [comment]
Applying \mathclap to the underset argument of \sum (instead of using \smashoperator at all) works as a replacement it turns out. Thanks to @Mico for that.

**Comment by car222222** [comment]
@davidcarlisle writes: Transparency is a weird beast in PDF:-)

Does that imply that there are systems in which Transparency is not weird?? :-)

Good to know that there is a workaround but it would be good to investigate sometime what is going on here: thanks for all the suggestions!

**Comment by davidcarlisle** [comment]
an example from Ulrike that I have extended a bit

```
\documentclass[xcolor={rgb}]{beamer}
\setbeamercovered{transparent}
\setbeamertemplate{navigation symbols}{}
\usepackage{mathtools}
\newsavebox\testbox
\begin{document}
\begin{frame}[plain,t]
\begin{align*}
\onslide<2->{&xxxxx \sbox\testbox{abc}\usebox\testbox 
&xxxxx \setbox\testbox\hbox{abc}\usebox\testbox }
\end{align*}
\end{frame}
\end{document}
```

note sbox fails but setbox works,  sbox assumes the current colour may be pushed/popped but it seems beamers "transparency" is setting light grey text directly, we can probably work around that somewhere.

**Comment by marmotghost** [comment]
I see. So the guess that saving the box is the problem was actually correct. (Of course I didn't know that beamer has that problem.)

**Comment by marmotghost** [comment]
The following avoids the `\savebox` problem.
```
\documentclass[xcolor={rgb}]{beamer}
\setbeamercovered{transparent}
\setbeamertemplate{navigation symbols}{}
\usepackage{mathtools}
\newsavebox\testbox
\begin{document}
\begin{frame}[plain,t]
\begin{align*}
\onslide<2->{&xxxxx \sbox\testbox{\color{.}abc}\usebox\testbox 
&xxxxx \setbox\testbox\hbox{abc}\usebox\testbox }
\end{align*}
\end{frame}
\end{document}
```

**Comment by daleif** [comment]
From the discussion above, this isn't really a `mathtools` problem. Can be reopened later if this needs to be fixed from the `mathtools` side of things
