### ISSUE TITLE
\cramped changes content width

### ISSUE THREAD

**Issue by RuixiZhang42** [latex3/mathtools#18]
`\cramped` is not supposed to change the width of its content. Here is a MWE illustrating the problem:
```latex
\documentclass{article}
\usepackage{mathtools}
\usepackage{graphicx} % for \scalebox
\begin{document}
\noindent
\scalebox{6}%
  {$\bigl| \left.x^3\right|_{x=-1} \bigr|$}

\noindent
\scalebox{6}%
  {$\bigl| \cramped{ \left.x^3\right|_{x=-1} } \bigr|$}
\end{document}
```
![cramped](https://user-images.githubusercontent.com/39968857/102004036-d8a28a00-3cda-11eb-94f1-cb9786b95827.png)

Notice how the `\left.` on the second line was completely gone. This is because `\MT_cramped_internal:Nn` does `\nulldelimiterspace=\z@`, which causes *every null delimiter in its content to be zero*, which is wrong.

## Proposed fix
Replace https://github.com/latex3/mathtools/blob/49e7124494eaa39bf2e65fe73fa6b475e5937984/mathtools.dtx#L5905 with
```latex
  \sbox\z@{$\m@th#1\kern-\nulldelimiterspace\radical\z@{#2}$}
```

**Comment by RuixiZhang42** [comment]
A more revealing MWE: Since `\frac` has “null delimiters” on both sides, we end up with a “doubly” narrow fraction if it were placed inside a `\cramped`.
```latex
\documentclass{article}
\usepackage{mathtools}
\usepackage{graphicx} % for \scalebox
\begin{document}
\noindent
\scalebox{6}%
  {$\bigl\langle (\frac{1}{2})^{n^k} \bigr\rangle$}

\smallskip

\noindent
\scalebox{6}%
  {$\bigl\langle \cramped{ (\frac{1}{2})^{n^k} } \bigr\rangle$}
\end{document}
```
![crampedfrac](https://user-images.githubusercontent.com/39968857/102017576-cdc91300-3d35-11eb-9a45-d0f4807296bc.png)

**Comment by daleif** [comment]
Should now be fixed in the sources. I'll have a look at the others over xmas.
