### ISSUE TITLE
Suggestions for the documentation

### ISSUE THREAD

**Issue by Rimole** [latex3/mathtools#21]
Thank you very much for your work. I have some suggestions for the mathtools documentation:

3.1.3 Smashing an operator
"Above we shoved" -> showed (w instead of v), please.

3.6.1 Expert use
The first box goes over the border of the page - please include a line break.

3.7.2 Vertically centered colon
cf. also the colonequals package

4.3 Declaring math sizes
"The fix was added to the LATEX kernel i 2015."
"in 2015" instead of "i 2015"?

References
+ "Available from CTAN as file"... Could you provide links, please?
+ For Ref. 1: https://www.tug.org/TUGboat/tb22-4/tb72perlS.pdf
+ [7]: The "." is missing at the end.

**Comment by daleif** [comment]
Incorporated into the documentation thanks for the suggestions.
