### ISSUE TITLE
spaces in messages

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/mathtools#30]
Currently every use of `mathtools` produces the log

```
LaTeX Info: Thecontrolsequence`\('isalreadyrobust on input line 130.
LaTeX Info: Thecontrolsequence`\)'isalreadyrobust on input line 130.
LaTeX Info: Thecontrolsequence`\['isalreadyrobust on input line 130.
LaTeX Info: Thecontrolsequence`\]'isalreadyrobust on input line 130.
```

as there are missing `~` in the messages in mathrools that are set with the mhsetup, expl3 style white space conventions.

Apart from fixing the general message these specific warnings could be avoided by skipping

```
  \EQ_MakeRobust\(
  \EQ_MakeRobust\)
  \EQ_MakeRobust\[
  \EQ_MakeRobust\]
```

as these have been robust in the format for some years so will always do nothing but warn.

**Comment by daleif** [comment]
I'll have a look at it over x-mas.

**Comment by daleif** [comment]
Ropbustifying \(\)\[\] removed in develop version
