### ISSUE TITLE
Incorrect year in date of latest update

### ISSUE THREAD

**Issue by heafnerj** [latex3/mathtools#36]
Line 3049 of `mathtools.dtx` lists the year as 2021 but it should be 2022. The error causes the version to be earlier than that needed to suppress warnings about `\MT_cramped_internal:Nn`. I copied `mathtools.sty` to my working directory and changed the date and the warnings disappeared.

**Comment by muzimuzhi** [comment]
Aha, https://github.com/latex3/mathtools/commit/470e28437da2944b951bef090b32f27548ca928e stepped year for `mathtools.drv` but not `mathtools.sty`.

**Comment by daleif** [comment]
Fixed and sent to CTAN

**Comment by daleif** [comment]
@heafnerj  did you delete the original question on tex.stackexchange? I cannot find it anymore.

**Comment by heafnerj** [comment]
> 

Hello. I just now saw this. Yes, I deleted my comment.
