### ISSUE TITLE
gathered environment with optional argument

### ISSUE THREAD

**Issue by SwitWu** [latex3/mathtools#38]
In the `mathtools` manual, it says that the following code
```
\[
    \begin{gathered}
      [p] = 100 \\
      [v] = 200
    \end{gathered}
\]
```
will produce unexpected result as `[p]` has been gobbled. However, in my test (windows 11, texlive2021 with package `amsmath` version 2.1) 
```
%test.tex
\documentclass{article}
\usepackage{amsmath}
\begin{document}
    \[
        \begin{gathered}
          [p] = 100 \\
          [v] = 200
        \end{gathered}
    \]
\end{document}
```
I found the result is correct.

So what's wrong?

**Comment by FrankMittelbach** [comment]
what's wrong is that this  no longer is gobbled but produces a warning (which you may have overlooked):
```
Package amsmath Warning: Bracket group [p] at formula start!
(amsmath)                It could be a misspelled positional argument.
(amsmath)                If it belongs to the formula add a \relax in
(amsmath)                front to hide it on input line 9.
```
amsmath does see the `[p]` but it isn't any longer gobbled because it is not meaningful as an optional argument and instead produces the above warning. If you use `[t]` instead it would be seen as a meaningful optional argument and acted upon.

So perhaps the mathtools documentation  could be altered somewhat but bracket groups at the start of the formula remain an issue.

**Comment by blefloch** [comment]
Are you sure @FrankMittelbach ?  With an up-to-date TeXLive, and running `pdflatex` on the following code, I don't get the warning.
```
\documentclass{article}
\usepackage{mathtools}
\begin{document}
\[
    \begin{gathered}
      [p] = 100 \\
      [v] = 200
    \end{gathered}
\]
\end{document}
```

**Comment by u-fischer** [comment]
@blefloch  load amsmath not mathtools to see the warning.

**Comment by FrankMittelbach** [comment]
the MWE was with amsmath, but you are right mathtools does suppress it (probably by altering some parts of gathered). but it doesn't fail either. So I guess, mathtool documentation (but also its coding should be checked because while not failing is good, not giving the warning is perhaps not.

**Comment by daleif** [comment]
Mathtools redefines `gathered` to use a nospace ifnextchar, such that if there is space between `\begin{gathered}` and `[arg]` then `[arg]` is not considered an argument for `gathered`

**Comment by FrankMittelbach** [comment]
@daleif guess then all that is wrong is that its manual does not give the right information about it if the  OP's statement is correct.

**Comment by daleif** [comment]
Text clearified in development version.
