### ISSUE TITLE
Enchanced \mathstrut

### ISSUE THREAD

**Issue by daleif** [latex3/mathtools#4]
Frank have suggested adding an extended \mathstrut such that one can make math struts that are slightly larger (or smaller) than the normal \mathstrut.

Suggested name: `\xmathstrut` and syntax

\xmathstrut[bommtom-enlarge]{enlarge}

Code suggestion from Frank

newbox\xmathstrut@box \newdimen\xmathstrut@dim
\def\xmathstrut{\@dblarg\xmathstrut@}
\def\xmathstrut@[#1]#2{\def\xmathstrut@dp{#1}%
   \vphantom{\mathpalette\xmathstrut@do{#2}}}
\def\xmathstrut@do#1#2{\setbox\xmathstrut@box\hbox{$#1($}%
   \xmathstrut@dim\dimexpr\ht\xmathstrut@box+\dp\xmathstrut@box\relax
   \ht\xmathstrut@box\dimexpr\ht\xmathstrut@box+#2\xmathstrut@dim
                             \relax
   \dp\xmathstrut@box\dimexpr\dp\xmathstrut@box+\xmathstrut@dp
                             \xmathstrut@dim
                             \relax
   \box\xmathstrut@box}

discussion to follow below

**Comment by daleif** [comment]
For the manual I suggest not mentioning scale, % etc

Just notice that given a positive decimal number it will be bigger, negative number, it will be smaller.

If given both arguments with the arguments being unequal (\xmathstrut[A]{A} = \xmathstrut{A}) then the change will result in a strut that is not symmetric proportionally to the values given.

**Comment by wspr** [comment]
I think not mentioning the scale factor is a problem. The obvious question when looking up the documentation is “what does the number refer to?”.

If \xmathstrut{0.1} adds 10% of the total height to the top and to the bottom why can’t you just say that?

I think you should also state (if you don’t already) that \xmathstrut{0} is equivalent to \mathstrut.

**Comment by car222222** [comment]
@wspr Maybe your suggested more explicit wording could go in as a supplementary paragraph, signposted as:

“More detail on the exact calculation of the size of an xmathstrut . . . “

**Comment by daleif** [comment]
> I think not mentioning the scale factor is a problem. The obvious question when looking up the documentation is “what does the number refer to?”. If \xmathstrut{0.1} adds 10% of the total height to the top and to the bottom why can’t you just say that? I think you should also state (if you don’t already) that \xmathstrut{0} is equivalent to \mathstrut.

I think the precise meaning of the scale factor etc just makes explaining the macro more difficult. 10% of what? Using the right amount in the argument will be a matter of trial and error anyway.

**Comment by car222222** [comment]
@daleif  Whilst I agree with you that the ‘headline documentation’ should probably not be too specific, I think that all the ghastly details need to be written down somewhere.

**Comment by davidcarlisle** [comment]
On Sun, 15 Mar 2020 at 10:09, Chris Rowley <notifications@github.com> wrote:

> @daleif <https://github.com/daleif> Whilst I agree with you that the
> ‘headline documentation’ should probably not be too specific, I think that
> all the ghastly details need to be written down somewhere.
>
>
>
The details don't even have to be too ghastly,   I think it just needs one
line adding.

change

 %          Here the
%  \meta{increase} is a decimal number, say, \verb|0.1|. If the number
%  is \emph{negative}, it will be a \emph{decrease} in size.
%


to


 %          Here the
%  \meta{increase} is a decimal number, say, \verb|0.1|. If the number
%  is \emph{negative}, it will be a \emph{decrease} in size.
% In either case, the number is a fraction of the total height of a
standard math strut
% in the current math style.

**Comment by car222222** [comment]
@davidcarlisle Maybe you really mean something more like this:

In either case, the number specified is used to calculate the absolute amount of change in size: as this fraction of the total height plus depth of the standard math strut in the current math style.

**Comment by car222222** [comment]
My attempt is not quite grammatical, needs adjustment.

**Comment by daleif** [comment]
The problem with being too specific is the implementation. \xmathstrut{0.1} is not just adding 0.1 x totalheight(mathstrut) is it actually twice that. 

(1) the algorithm is not difficult to understand for users who want details.

(2) It may be hard for users to grasp that they are actually adding twice as much as they think they are.

**Comment by daleif** [comment]
Dang, keep forgetting mentioning the issue number in the commit. I changed the wording a little

**Comment by FrankMittelbach** [comment]
Am 15.03.20 um 17:11 schrieb daleif:
> (2) It may be hard for users to grasp that they are actually adding 
> twice as much as they think they are.

sorry but I really do see where there should be any difficulty  if you 
are describing it in terms of

  \xmathstrut{0.1} -> adds 10% of the ( size above and 10% below


  \xmathstrut[0.1]{0.2} -> adds 10% of the ( size  below and 20% extra above

======

In my opinion there is only a difficulty if you try to make 
\xmathstrut{0.1} and 5% above and below because then it is hard to 
explain nicely what [0.1]{0.2}  does

**Comment by daleif** [comment]
I'll rewrite it again later

**Comment by car222222** [comment]
> (1) the algorithm is not difficult to understand for users who want details.
Good: so please write down somewhere these easy to understand details, noting that this writing will also be easy.
Or should we translate this statement to “read the code if you want to know the details”?   
At least tell people that this is the only way to discover the details.
Or maybe (better) refer to the documentation of the code, which must anyway contain a textual description of the algorithm (or not?).

**Comment by car222222** [comment]
Try formatting that properly:

>  (1) the algorithm is not difficult to understand for users who want details.

Good: so please write down somewhere these easy to understand details, noting that this writing will also be easy.
Or should we translate this statement to “read the code if you want to know the details”?
At least tell people that this is the only way to discover the details.
Or maybe (better) refer to the documentation of the code, which must anyway contain a textual description of the algorithm (or not?).

**Comment by daleif** [comment]
Better now? If not please provide a text

**Comment by davidcarlisle** [comment]
@daleif  looks fine to me, thanks.

**Comment by car222222** [comment]
Excellent!  But I noticed one place I would have put in an extra word:

 (thus 20\% added in total)  ==>   (thus 20\% gets added in total)

**Comment by daleif** [comment]
fixed

**Comment by daleif** [comment]
Everyone seems happy with the wording.

Closed
