### ISSUE TITLE
Handling `\protect\big` in say `\norm[\protect\big]{x}` for sections

### ISSUE THREAD

**Issue by daleif** [latex3/mathtools#40]
In https://tex.stackexchange.com/q/639107/3929 we have the MWE below, which fails when `\tableofcontents` is added.

```
\documentclass{scrartcl}
\usepackage{amsmath}
\usepackage{mathtools}

\DeclarePairedDelimiter{\norm}{\lVert}{\rVert}

\begin{document}

% \tableofcontents

\section{This works: $\norm{x}$}
\section{Also works: $\norm*{x}$}
\section{This fails: $\norm[\big]{x}$}

\end{document}
```

This is down to premature expansion of `\big`. Ok, then we just protect it right: `\protect\big`.

But that gives another error because `\norm[\foo]{x}` treats `\foo` as a string, strips the ``\`` in order to use `\fool` and `\foor` instead.

This fails when the arg is `\protect\foo` as it instead removes the ``\`` from `\protect` (at least as far as I see it).

We can solve it using `etoolbox` and `\protecting{\norm[\foo]{x}}`, but would like to do this directly inside the definition for `\norm`.

**Comment by daleif** [comment]
For now I'll just leave this issue with note 3 in section 3.6. This is part down to `\norm[\big]{foo}` being bad syntax, \norm[big]{foo}` might have been better, and partly because `\big` and friends are not robust.

Egreg mentioned in his response to the stackexchange question `\robustify\big` which is the solution I've mentioned in the manual.

**Comment by davidcarlisle** [comment]
We will make this robust in amsmath (it has already been made robust in the format but then amsmath makes it not robust again just due to historical code)

**Comment by FrankMittelbach** [comment]
I have made most amsmath commands robust (matching those in the kernel). This is currently moving into the next `-dev-`release and will show up in the main release in June.
