### ISSUE TITLE
broken underbrace/overbrace when used after libertinus

### ISSUE THREAD

**Issue by tpapp** [latex3/mathtools#43]
MWE:
```latex
\documentclass[a4paper]{article}
\usepackage{libertinus}         % using mathtools BEFORE works fine
\usepackage{fontspec}
\setmathfont{Latin Modern Math}
\usepackage{mathtools}
\begin{document}
\begin{equation}
  \underbrace{g_u \lambda_u \Gamma_u}_{\text{example}} = 
    \underbrace{\int g_e(\varphi) \delta(\varphi) d\varphi}_{\text{example}}
\end{equation}
\end{document}
```
results in 
![mathtools](https://user-images.githubusercontent.com/84122/170270565-565e76d9-abf3-4121-80a0-994c132b3b03.png)

using TeXLive 2021.20220204-1 in Ubuntu 22.04. Exchanging the order of `libertinus` and `mathtools` fixes the issue.

(apologies if I am reporting in the wrong place, if this is not a bug in this package then please tell me where to take it)

**Comment by davidcarlisle** [comment]
I'd say it's a bug in the document, if you load a package that redfines the math font encoding you need to arrange not to load conflicting packages later. `unicode-math` used to have a requirement that `amsmath` was loaded before it. It resolves that now by always loading `amsmath` but with `mathtools` you still need to take care of the loading order.

It's possible that `mathools` could detect that it is loaded after unicode-math and change its behaviour but `unicode-math` isn't the only package that changes encodings here and catching all package dependencies isn't easy. 

unicode-math does document

> Note that amsmath should be loaded before unicode-math to avoid conflicts,
and it will be loaded automatically if not requested earlier in the preamble.

mathtools also wants to be loaded earlier (but is not auomatically loaded)

**Comment by daleif** [comment]
I might add a check for `unicode-math` and if it is already loaded issue a warning that `mathtools` needs to be loaded before `unicode-math`?

**Comment by tpapp** [comment]
@daleif: that would be very useful and would resolve the issue for me. My main problem was not the breaking braces *per se*, but narrowing it down to the MWE above which then allowed me to find a workaround. Having an error or warning message about it would have simplified the process.

**Comment by daleif** [comment]
I've added a warning if `mathtools` is loaded after `unicode-math`.
