### ISSUE TITLE
xmapsto

### ISSUE THREAD

**Issue by KuznetsovAleksey** [latex3/mathtools#45]
mathtools 2022/06/29 v1.29
unicode-math 2020/01/31 v0.8q

\documentclass{article}
\usepackage{mathtools}
\usepackage{unicode-math}
\begin{document}

\[ \xmapsto[1]{2} \]

\end{document}

\xmapsto  provides 7→ instead of \mapsto symbol

**Comment by daleif** [comment]
I'm not sure this is a `mathtools` issue since (1) it works just fine without `unicode-math` and the issue persists if we define `\xmapsto` without `mathtools` (it is exactly the same definition)

```
\documentclass{article}
% \usepackage{mathtools}
\usepackage{amsmath}

\makeatletter
\newcommand*\@mapstofill{\arrowfill@{\mapstochar\relbar}\relbar\rightarrow}
\providecommand*\xmapsto[2][]{%
  \ext@arrow 0395\@mapstofill{#1}{#2}}

\makeatother

\usepackage{unicode-math}
\begin{document}

\[
  \xmapsto[1]{2}
\]

\end{document}
```

The 7 comes from `\mapstochar` which is the end bit. It might seem that `unicode-math` is not remapping it?

**Comment by daleif** [comment]
Relevant thread from `unicode-math` (thanks to Ulrike)

https://github.com/wspr/unicode-math/issues/197

**Comment by KuznetsovAleksey** [comment]
The problem is related to \xmapsto 
since lualatex + unicode-math for $\mapsto$ print the mapsto symbol.

Please, note the problem in next issue of the mathtools manual.
unicode-math is rarely updated and it's bug list is long.

**Comment by daleif** [comment]
Yes, but \mapsto (as a symbol) exists in unicode. `\xmapsto` needs to build `|->` and gets the `|` from `\mapstochar` which is not defined in unicode and thus is missing from the font. Note that `amsmath` defines `\mapsto` as `\mapstochar\righarrow`, unicode-math just overwrites `\mapsto` to point at the unicode char.

**Comment by KuznetsovAleksey** [comment]
Dear Lars,
sorry, if this request is in the wrong place.
Would you like to add to mathtools something similar

\newcommand\stack[2]{\genfrac{}{}{0pt}{}{#2}{#1}}
\newcommand\tstack[2]{\genfrac{}{}{0pt}{1}{#2}{#1}}
\newcommand\dstack[2]{\genfrac{}{}{0pt}{0}{#2}{#1}}

These constructions are similar to binoms without parenthesis or fractions without delimiting lines.
They complement the \overset an \underset constructions.

Kind regards,
Alexey

**Comment by daleif** [comment]
Please post those as a separate issue/request. Though, it don't see how they are much use to other than very few people.

And I don't see how they complement \overset etc, it is two different things

**Comment by daleif** [comment]
As this is not a mathtools problem per se, I'm closing this.
