### ISSUE TITLE
Setting `centercolon` to `false` crashes if it has never been `true`

### ISSUE THREAD

**Issue by psisquared2** [latex3/mathtools#49]
Basically, as the title says, `\mathtoolsset{centercolon=false}` crashes if no `\mathtoolsset{centercolon}` has been called before.

```latex
\documentclass[a4paper]{article}

\usepackage{mathtools}
\mathtoolsset{centercolon=false}

\begin{document}\end{document}
```

Error log:
```
! Undefined control sequence.
<argument> \MT_true_false_error:n 
                                  \@nameuse {MT_active_colon_false:}
l.7 \mathtoolsset{centercolon=false}
                                    
The control sequence at the end of the top line
of your error message was never \def'ed. [...]
```

Code that doesn't crash:
```latex
\documentclass[a4paper]{article}

\usepackage{mathtools}
\mathtoolsset{centercolon=true}
\mathtoolsset{centercolon=false}
\mathtoolsset{centercolon=false}

\begin{document}\end{document}
```

System: Windows 10, MiKTeX 22.8, mathtools version 1.29.

**Comment by daleif** [comment]
Thanks, for now this can fix it

```
\MHInternalSyntaxOn
\def\MT_active_colon_false: {}
\MHInternalSyntaxOff

\mathtoolsset{centercolon=false}
```

basically `\MT_active_colon_false: ` is not defined until `centercolon=true` has been executed, because who would ever run `centercolor=false` before runing `centercolor=true`

I'll fix it in the next version

**Comment by psisquared2** [comment]
Thanks! My use case is that I modify `\tikz` to call `\mathtoolsset{centercolon=false}` beforehand due to well-known issues with tikz and active colons. If I now globally disable `centercolon=true` for whatever reason, the document no longer compiles.
