### ISSUE TITLE
Empheq vs amsart

### ISSUE THREAD

**Issue by daleif** [latex3/mathtools#5]
From https://tex.stackexchange.com/q/532863/3929

Compare the result with and without `amsrt`

```
\documentclass[fleqn,leqno]{article}
%\documentclass[fleqn]{amsart}
\usepackage{amsmath}
\usepackage{empheq}
\usepackage{xcolor}
\newcommand*\mybluebox[1]{\colorbox{blue!20}{\hspace{1em}#1\hspace{1em}}}

\begin{document}
\begin{enumerate}
\item We have
\begin{empheq}[box=\mybluebox]{equation}
f(x)=g(x)
\end{empheq}
\begin{empheq}[box=\mybluebox]{align}
f(x)=f(x)=g(x)
\end{empheq}
\item etc.
\item We have
\begin{equation}
f(x)=g(x)
\end{equation}
\begin{align}
f(x)=f(x)=g(x)
\end{align}
\item etc.
\end{enumerate}
\end{document}
```

With `amsart` the width of the box on the `empheq` envs are wrong

**Comment by daleif** [comment]
Playing with the contents of `amsart` it seems to be related to

```
\def\fullwidthdisplay{\displayindent\z@ \displaywidth\columnwidth}
\edef\@tempa{\noexpand\fullwidthdisplay\the\everydisplay}
\everydisplay\expandafter{\@tempa}
```
at least if I in the MWE above add

```
\def\fullwidthdisplay{}
```

then the boxes are no longer the wrong width, though now the `leqno` placement is wrong.

**Comment by daleif** [comment]
Observation it seems to only be `align` that have issues, `equation`, `gather` and even `alignat` seems fine.

**Comment by daleif** [comment]
Just under fleqn this patch helps

```
\usepackage{xpatch}
\MHInternalSyntaxOn
% fails with error if the patch does not work
% only fixes the align problem under the 'fleqn' toption!!
\xapptocmd\EQ_find_displaywidth_i:{%
  \MH_addtolength:dn \l_EQ_displaywidth_dim{\@mathmargin}
}{\typeout{ok}}{\ERROR}
\MHInternalSyntaxOff
```

but does not work for non-fleqn and does not explain why it is needed in the first place.

Where does the algorithm go wrong by amsart setting \displaywidth=\columnwidth?

**Comment by daleif** [comment]
A better patch

```
 \xpatchcmd{\EQ_initialize:}{%
   \l_EQ_temp_linewidth_dim\linewidth%
 }{%
   \l_EQ_temp_linewidth_dim\columnwidth%
 }{\typeout{ok}}{\ERROR}
```

The culprit to it all is this

```
\def\EQ_initialize:{%
  \m@th
  \MH_let:NwN\SetTagPlusEndMark\EQ_tag_plus_endmark:
  \MH_let:NwN\SetOnlyEndMark\EQ_only_endmark:
  \l_EQ_temp_linewidth_dim\linewidth % <-------------
  \g_EQ_toprow_height_dim\z@
  \g_EQ_bottomrow_depth_dim\z@
  \g_EQ_toptag_height_dim\z@
  \g_EQ_bottomtag_depth_dim\z@
  \g_EQ_widesttag_dim\z@
  \xdef\g_EQ_latest_nonzerodepth_row_fint{\z@}
  \edef\EQ_restore_tex_delimiter:{%
    \delimiterfactor\the\delimiterfactor
    \delimitershortfall\the\delimitershortfall\relax}%
  \g@addto@macro\EQ_complete_mathdisplay:
                \EQ_restore_tex_delimiter:
  \delimitershortfall\EmphEqdelimitershortfall
  \delimiterfactor\EmphEqdelimiterfactor
  \MH_let:NwN\intertext@\EQ_intertext:
  \EQ_displaybreak:}
````

in `amsart` `\displaywidth >= \linewidth` and `\linewidth` is of course smaller in lists

amsart is setting `\displaywidth` in `\everydisplay` and `\EQ_initialize:` is issued long before any display math is involved. So need some way of extracting that information from `\everydisplay`

**Comment by daleif** [comment]
As `amsart` defines

```
\def\fullwidthdisplay{\displayindent\z@ \displaywidth\columnwidth}
```
One solution could be

```
\def\EQ_initialize:{%
  \m@th
  \MH_let:NwN\SetTagPlusEndMark\EQ_tag_plus_endmark:
  \MH_let:NwN\SetOnlyEndMark\EQ_only_endmark:
  \l_EQ_temp_linewidth_dim\linewidth
  \@tempdima\z@
  \begingroup
  \ifdefined\fullwidthdisplay\relax
    \fullwidthdisplay
    \global\@tempdima\displaywidth
  \fi
  \endgroup
  \ifdim\@tempdima>\z@
    \l_EQ_temp_linewidth_dim\@tempdima
  \fi
  \@tempdima\z@  
  \g_EQ_toprow_height_dim\z@
  \g_EQ_bottomrow_depth_dim\z@
  \g_EQ_toptag_height_dim\z@
  \g_EQ_bottomtag_depth_dim\z@
  \g_EQ_widesttag_dim\z@
  \xdef\g_EQ_latest_nonzerodepth_row_fint{\z@}
  \edef\EQ_restore_tex_delimiter:{%
    \delimiterfactor\the\delimiterfactor
    \delimitershortfall\the\delimitershortfall\relax}%
  \g@addto@macro\EQ_complete_mathdisplay:
                \EQ_restore_tex_delimiter:
  \delimitershortfall\EmphEqdelimitershortfall
  \delimiterfactor\EmphEqdelimiterfactor
  \MH_let:NwN\intertext@\EQ_intertext:
  \EQ_displaybreak:}
```
I would of course be better to extract `\displaywidth` directly from `\everydisplay`, I just don't see how.

**Comment by daleif** [comment]
That seems to work for everything, except flalign. Back to work

**Comment by daleif** [comment]
This was actually not enough. Further investigation showed that because of the `\displaywidth` we cannot rely on the width of the typeset material to match up with the box it is being typeset with in. The value of `\alignsep@` will be wrong.

A fix has been found. Though testing also reviled that `multline` and `flalign` has issues in general. For now these will be ignored and hopefully fixed at a later date.

**Comment by wspr** [comment]
Can you log those issues in the amsmath repository so they’re not lost/forgotten in the future? (Apologies if I missed them there already.)

**Comment by daleif** [comment]
@wspr 

That depends on which issues you are refering to.

Nothing `amsart` seems to be doing affects the way `amsmath` operates. It is just when we attempt to use `amsmath` for stuff that is was not designed for that these show their ugly faces.

The only issue that is amsmath related if probably the fleqn+leqno bug in single-column flalign. That probably needs to be  registered in `amsmath`, though Ulrike shoed that is has been in the bug database since like 2003!

**Comment by daleif** [comment]
fixed
