### ISSUE TITLE
I've expected \MT_cramped_internal:Nn warning

### ISSUE THREAD

**Issue by unalmis** [latex3/mathtools#52]
Similar to #24 , but apparently this was not resolved.
I am using the default latex package in Fedora 37 which can be obtained with `sudo dnf install texlive-scheme-medium`. Running `tlmgr info <package>` gives cat-version 0.8q for `unicode-math`, cat-version 1.27 for `mathtools`, and cat-version 1.9 for `lualatex-math`.

Minimal working example:
```latex
\documentclass{article}
\usepackage{mathtools}
% load after mathtools (which loads amsmath)
\usepackage[
    warnings-off={mathtools-colon, mathtools-overbracket},
]{unicode-math}
\begin{document}
\end{document}
```

Produced warning:
```
Package lualatex-math Warning: I've expected \MT_cramped_internal:Nn to have
(lualatex-math)                the meaning
(lualatex-math)                macro:#1#2->\sbox \z@ {$\m@th
(lualatex-math)                #1\nulldelimiterspace =\z@ \radical \z@
(lualatex-math)                {#2}$}\ifx #1\displaystyle \dimen@ =\fontdimen
(lualatex-math)                8\textfont 3\advance \dimen@ .25\fontdimen
(lualatex-math)                5\textfont 2\else \dimen@ =1.25\fontdimen 8\ifx
(lualatex-math)                #1\textstyle \textfont \else \ifx
(lualatex-math)                #1\scriptstyle \scriptfont \else
(lualatex-math)                \scriptscriptfont \fi \fi 3\fi \advance \dimen@
(lualatex-math)                -\ht \z@ \ht \z@ =-\dimen@ \box \z@ ,
(lualatex-math)                but it has the meaning
(lualatex-math)                macro:#1#2->{\ensuremath {\use:c
(lualatex-math)                {cramped\cs_to_str:N #1}#2}}.
```
The full log is attached.
[test.log](https://github.com/latex3/mathtools/files/11032292/test.log)

**Comment by muzimuzhi** [comment]
> cat-version 1.9 for `lualatex-math`.

I think you need either `lualatex-math` 1.10 or 1.11, see https://github.com/phst/lualatex-math/commit/ad51bb060107da4e5cc82e16e19243049fe97a58 and https://github.com/phst/lualatex-math/commit/300c67cc8b5ca2e70378e98a6f8e5490a7f4ff36.
