### ISSUE TITLE
Awkward spacing with some operators and paired delimiter

### ISSUE THREAD

**Issue by Enivex** [latex3/mathtools#53]
If I define 
`\DeclarePairedDelimiter{\brak}{\lbrack}{\rbrack}`
then spacing will often be way to cramped (in my opinion) between operators and large versions of the delimiter.

`\lim_{n\to \infty}\brak*{\int_0^\infty}\quad \sum_{n\to \infty}\brak*{\int_0^\infty}`

displays as

![image](https://user-images.githubusercontent.com/2191754/228629469-d27e6399-b3d6-4f6a-9692-9cee56ede426.png)

The reason for this is obviously the `\mathopen` in the definition. Which is great for operators like `\sin`, but not so great in these cases (in my opinion).  I much prefer to do something like 

` \lim_{n\to \infty}{}\brak*{\int_0^\infty}\quad \sum_{n\to \infty}{}\brak*{\int_0^\infty}`

which displays as

![image](https://user-images.githubusercontent.com/2191754/228630001-5b9911db-21e1-4fb6-b5d5-550bf50174ff.png)

The $n \to \infty$ and $n=0$ are no longer uncomfortably close to the delimiter.

My question is: Is there a better way to handle this than having to manually add {} to add space in these cases?

(This also happens with other delimiters, but I chose brackets to illustrate the issue)

**Comment by davidcarlisle** [comment]
I'd say this is by design, although rather than add `{}` each time you could adjust the definition

```
\DeclarePairedDelimiter{\brakinner}{\lbrack}{\rbrack}
\newcommand\brak{{}\brakinner}
```

**Comment by juhaszp95** [comment]
Hello,

Somewhat related to this (although not exactly) is that I get awkward spacing when using Libertinus with `mathtools`. Consider the following MWE (in LuaTeX):

```
\documentclass[12pt]{article}
\usepackage{libertinus-otf}

\usepackage{mathtools}
\DeclarePairedDelimiter{\abs}{\lvert}{\rvert}

\begin{document}
	$c\lvert c \rvert \ c\abs{c} \ c\abs*{c}$
\end{document}
```

I get the following output:
![image](https://user-images.githubusercontent.com/36235630/233799466-0ce02d7e-09ca-40ad-a4c5-3eab33a14e48.png)

Notice how the spacing is off in the last case, and `c` comes very close to colliding with `|`. I'm not sure if this is a font issue or a `mathtools` issue, but given the spacing is different between the starred and non-starred version of the command, I thought it might be the latter.

**Comment by daleif** [comment]
First of, please don't hijack questions (make your own issue). Secondly the problem is also present without `mathtools`: `$c\lvert c \rvert\quad \left\lvert c \right\rvert$` so I don't think this has anything to do with `mathtools`.

**Comment by daleif** [comment]
As David mentioned the \mathopen is by design. Will not be changed,
