### ISSUE TITLE
tagform applied unevenly

### ISSUE THREAD

**Issue by juhaszp95** [latex3/mathtools#54]
Hi There,

I'm trying to make my equation tags use the capital form of the numbers/letters/symbols, which is especially important in the appendix where e.g. Eq. (A.1) would look 'uneven' otherwise. However, when I declare the relevant `tagform`, it only seems to apply to a part of the tag.

MWE (to be run in LuaLaTeX):
```
\documentclass{article}
\usepackage{libertinus-otf}
\usepackage{mathtools}

\begin{document}
	\newtagform{caps}[\addfontfeatures{Letters=Uppercase}]{(}{)}
	\usetagform{caps}

	%\let\oldeq\theequation
	%\renewcommand\theequation{\addfontfeatures{Letters=Uppercase}\oldeq}

	\begin{equation}
		bla
	\end{equation}	
\end{document}
```

This gives me:
![image](https://user-images.githubusercontent.com/36235630/235318652-7cdce3da-02ac-4a58-9478-d9b474cb3adf.png)

Notice the different brackets. Basically, I'd like both the brackets and the letters/numbers in the tag itself to use `\addfontfeatures{Letters=Uppercase}`. The commented lines in the code let me apply it to the number itself, but not the brackets. Any help would be appreciated.

**Comment by muzimuzhi** [comment]
In current implementation, the optional argument of `\newtagform{<name>}[<inner_format>]{<left>}{<right>}`, `inner_format`, is inserted after `<left>` hence is expected to influence the equation number only, by taking it as argument. 
https://github.com/latex3/mathtools/blob/58d14613fc469718fe85849dfcfcee2a605c2b2b/mathtools.dtx#L3311-L3313
https://github.com/latex3/mathtools/blob/58d14613fc469718fe85849dfcfcee2a605c2b2b/mathtools.dtx#L3322-L3332

As a workaround you can try prepending the format code to `<left>`, like `\newtagform{brackets2}{\addfontfeatures{Letters=Uppercase}(}{)}`

```tex
\documentclass{article}
\usepackage{libertinus-otf}
\usepackage{mathtools}

\begin{document}
	\newtagform{brackets2}[\addfontfeatures{Letters=Uppercase}]{(}{)}
	\usetagform{brackets2}

	\begin{equation}
		bla
	\end{equation}

	\renewtagform{brackets2}{\addfontfeatures{Letters=Uppercase}(}{)}

	\begin{equation}
		bla
	\end{equation}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/235328820-526357e7-1cad-4315-81dd-c8e3702e2cb2.png)

**Comment by juhaszp95** [comment]
Perfect, this solves my problem, many thanks. I'll keep the issue in case you want to change the implementation, but feel free to close it if you like.

**Comment by daleif** [comment]
Addd a brace pair such that anything in `#2` only applies to `{##1}`
